"""Agent service boundaries."""

from stat_arb.agents.backtest import (
    BacktestAgentInput,
    BacktestAgentRunResult,
    run_backtest_agent_persistence,
)
from stat_arb.agents.critic import (
    CriticCostRealismAssessment,
    CriticCostRealismEvidence,
    CriticCostRealismPolicy,
    CriticInsufficientTestingAssessment,
    CriticInsufficientTestingEvidence,
    CriticInsufficientTestingPolicy,
    CriticLookaheadAssessment,
    CriticLookaheadEvidence,
    CriticLookaheadPolicy,
    CriticOverfittingAssessment,
    CriticOverfittingEvidence,
    CriticOverfittingPolicy,
    CriticWeakAssumptionAssessment,
    CriticWeakAssumptionEvidence,
    CriticWeakAssumptionPolicy,
    detect_cost_realism,
    detect_insufficient_testing,
    detect_lookahead_bias,
    detect_overfitting,
    detect_weak_assumptions,
)
from stat_arb.agents.hypothesis import (
    HypothesisGenerationConfig,
    HypothesisGenerationResult,
    HypothesisLinkingConfig,
    HypothesisMemorySearchResult,
    HypothesisNoveltyAssessment,
    HypothesisNoveltyConfig,
    HypothesisUniverseAsset,
    generate_rule_based_hypotheses,
)
from stat_arb.agents.statistical_testing import (
    StatisticalTestingInput,
    StatisticalTestingRunResult,
    run_statistical_testing,
)

__all__ = [
    "BacktestAgentInput",
    "BacktestAgentRunResult",
    "CriticCostRealismAssessment",
    "CriticCostRealismEvidence",
    "CriticCostRealismPolicy",
    "CriticInsufficientTestingAssessment",
    "CriticInsufficientTestingEvidence",
    "CriticInsufficientTestingPolicy",
    "CriticLookaheadAssessment",
    "CriticLookaheadEvidence",
    "CriticLookaheadPolicy",
    "CriticOverfittingAssessment",
    "CriticOverfittingEvidence",
    "CriticOverfittingPolicy",
    "CriticWeakAssumptionAssessment",
    "CriticWeakAssumptionEvidence",
    "CriticWeakAssumptionPolicy",
    "HypothesisGenerationConfig",
    "HypothesisGenerationResult",
    "HypothesisLinkingConfig",
    "HypothesisMemorySearchResult",
    "HypothesisNoveltyAssessment",
    "HypothesisNoveltyConfig",
    "HypothesisUniverseAsset",
    "StatisticalTestingInput",
    "StatisticalTestingRunResult",
    "detect_cost_realism",
    "detect_insufficient_testing",
    "detect_lookahead_bias",
    "detect_overfitting",
    "detect_weak_assumptions",
    "generate_rule_based_hypotheses",
    "run_backtest_agent_persistence",
    "run_statistical_testing",
]
